name: SLSA3 Builder internal wrapper
description: SLSA3 Builder internal wrapper

inputs:
  slsa-workflow-inputs:
    description: 'All the inputs formatted as a JSON map'
    type: string
    required: true

  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true

  slsa-workflow-secret1:
    description: 'secret1 is unused'
    type: string
    required: false

  slsa-workflow-secret2:
    description: 'secret2 is unused'
    type: string
    required: false

runs:
  using: 'composite'
  steps:
    # NOTE: the repository is already cloned by the caller, so there's no need to
    # checkout ourselves.

    # This calls the main Action, e.g., ./../__TOOL_CHECKOUT_DIR__/<path/to/action>
    # if path is left empty, the Action's action.yml is located at the root of the repository.
    - name: Run main sbom-action Action
      uses: ./../__TOOL_CHECKOUT_DIR__
      with:
        message: ${{ fromJson(inputs.slsa-workflow-inputs).message }}
        file: ${{ fromJson(inputs.slsa-workflow-inputs).file }}
        version: ${{ fromJson(inputs.slsa-workflow-inputs).version }}

    - name: Generate layout file
      id: generate-layout
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
        UNTRUSTED_OUTPUT_FILE: ${{ fromJson(inputs.slsa-workflow-inputs).file }}
      shell: bash
      run: |
        cat <<EOF | tee "$SLSA_OUTPUTS_ARTIFACTS_FILE" | jq
        {
            "version": 1,
            "attestations":
            [
                {
                    "name": "attestation.intoto",
                    "subjects":
                    [
                        "${UNTRUSTED_OUTPUT_FILE}"
                    ]
                }
            ]
        }
        EOF
